export interface User {
 userId: string,
 firstName: string,
 lastName: string,
 program: string,
 password: string,
 yearOfStudy: number,
 studentNumber:number,
 bio: string,
 profilePictureUrl: string,
 backgroundProfile: string,
 email: string,
 school: string,
 groups: string[],
 connections: string[],
 pages: string[],
 posts: string[],
 photos: string[],
 comments: string[]
}